---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Glance
      apt:
        name:
          - glance
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Keystone
      apt:
        name:
          - keystone
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Nova
      apt:
        name:
          - nova-compute
        state: latest
      when: ansible_distribution == "Ubuntu"


